// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Proveedores.Entities.Entities;

#nullable disable

namespace Proveedores.DataAccess.Context
{
    public partial class TAREA_PROVEEDORESContext : DbContext
    {
        public TAREA_PROVEEDORESContext()
        {
        }

        public TAREA_PROVEEDORESContext(DbContextOptions<TAREA_PROVEEDORESContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbProveedores> tbProveedores { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<tbProveedores>(entity =>
            {
                entity.HasKey(e => e.prov_ID)
                    .HasName("PK__tbProvee__43504EBE6769C705");

                entity.Property(e => e.prov_DireccionExacta).IsRequired();

                entity.Property(e => e.prov_DireccionExactaEmpresa).IsRequired();

                entity.Property(e => e.prov_Empresa).IsRequired();

                entity.Property(e => e.prov_NombreContacto).IsRequired();

                entity.Property(e => e.prov_SexoContacto)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.prov_TelefonoContacto).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}