// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Proveedores.Entities.Entities
{
    public partial class tbProveedores
    {
        public int prov_ID { get; set; }
        public string prov_Empresa { get; set; }
        public string prov_NombreContacto { get; set; }
        public string prov_TelefonoContacto { get; set; }
        public string prov_DireccionExacta { get; set; }
        public string prov_DireccionExactaEmpresa { get; set; }
        public string prov_SexoContacto { get; set; }
    }
}